baseURL = 'https://azure-skunk.cloudvent.net/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'PaperMod'
[params]
  # Agar link gambar selalu benar meski di sub-folder
  canonifyURLs = true
  relativeURLs = true
